In [21]:
import numpy as np

def is_diag(matrix: np.array) -> bool:
    return all([matrix[i][i] > sum(row)-matrix[i][i] for i, row in enumerate(matrix)])

In [22]:
A = np.array([
        [2,0,1],
        [1,3,1],
        [1,3,10]
])
print(f"Is the matrix A diagonally dominant? {is_diag(A)}")
print(A)

Is the matrix A diagonally dominant? True
[[ 2  0  1]
 [ 1  3  1]
 [ 1  3 10]]


In [20]:
B = np.array([
        [2,10,1],
        [1,3,1],
        [1,3,10]
])
print(f"Is the matrix A diagonally dominant? {is_diag(B)}")
print(B)

Is the matrix A diagonally dominant? False
[[ 2 10  1]
 [ 1  3  1]
 [ 1  3 10]]
